knp_paginator:
    page_range: 2
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: 'bootstrap_4_pagination.html.twig'
