app_utilisateur_index:
    path: /utilisateur
    controller: App\Controller\UtilisateurController::index
    methods: ['GET']
app_utilisateur_new:
    path: /utilisateur/new
    controller: App\Controller\UtilisateurController::new
    methods: ['GET', 'POST']

app_utilisateur_show:
    path: /utilisateur/show/{id}
    controller: App\Controller\UtilisateurController::show
    methods: ['GET']

app_utilisateur_edit:
    path: /utilisateur/edit/{id}
    controller: App\Controller\UtilisateurController::edit
    methods: ['GET', 'POST']

app_utilisateur_delete:
    path: /utilisateur/delete/{id}
    controller: App\Controller\UtilisateurController::delete
    methods: ['POST']
users_by_age_chart:
    path: /utilisateur/age_stat
    controller: App\Controller\UtilisateurController::usersByAgeChart

app_register:
    path: /utilisateur/register
    controller: App\Controller\UtilisateurController::register
    methods: ['GET', 'POST']

app_myprofile:
    path: /utilisateur/MonProfile
    controller: App\Controller\UtilisateurController::Myprofile
    methods: ['GET']
utilisateur_reset_password_submit:
    path: /utilisateur/reset-password/submitted
    methods: [POST]
    controller: App\Controller\UtilisateurController::resetPasswordSubmitted

app_edit_profile:
    path: /utilisateur/modifier-profil
    controller: App\Controller\UtilisateurController::editProfile
    methods: ['GET', 'POST']

app_edit_profile_password:
    path: /utilisateur/EditProfilePassword
    controller: App\Controller\UtilisateurController::EditProfilePassword
    methods: ['GET', 'POST']

app_reset_password_submited:
    path: /utilisateur/reset-password/submitted
    controller: App\Controller\UtilisateurController::resetPasswordSubmitted
    methods: ['GET']

reset_password:
    path: /utilisateur/reset-password
    controller: App\Controller\UtilisateurController::resetPassword
    methods: ['GET']

utilisateur_verify_reset_code:
    path: /utilisateur/verify-reset-code/{restToken}
    controller: App\Controller\UtilisateurController::verifyResetCode

reset_password_profil:
    path: /utilisateur/resetPassword/profil
    controller: App\Controller\UtilisateurController::resetPasswordProfile
    methods: ['GET', 'POST']

reset_password_profil_admin:
    path: /utilisateur/admin/resetPassword/profil
    controller: App\Controller\UtilisateurController::resetPasswordProfileAdmin
    methods: ['GET', 'POST']
app_index:
  path: /
  controller: App\Controller\Home::index
  methods: GET

app_index_admin:
  path: /admin
  controller: App\Controller\Home::indexAdmin
  methods: GET
user_role_statistics:
    path: utilisateur/user-role-statistics
    controller: App\Controller\UtilisateurController::userRoleStatistics
